
// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

import (
	"github.com/swaggo/swag"
)

func init() {
	swag.Register(swag.Name, &s{})
}

type s struct{}

func (s *s) ReadDoc() string {
	return `{
		"swagger": "2.0",
		"info": {
			"description": "This is a sample server.",
			"version": "1.0.0",
			"title": "Swagger Example API"
		},
		"host": "192.168.1.78:8080",
		"basePath": "/",
		"schemes": [
			"http"
		],
		"paths": {
			"/example": {
				"get": {
					"summary": "Example endpoint",
					"responses": {
						"200": {
							"description": "OK"
						}
					}
				}
			}
		}
	}`
}
