# .github/workflows/swagger-test.yml
name: Swagger Tests

on:
  push:
    paths:
      - 'swagger.yaml'
      - 'swagger_test.go'
      - '**.go'
  pull_request:
    paths:
      - 'swagger.yaml'
      - 'swagger_test.go'
      - '**.go'

jobs:
  test-swagger:
    name: Test Swagger Definition
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: stocks
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: aactions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true

    - name: Install dependencies
      run: |
        go mod download
        go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate Swagger docs
      run: swag init

    - name: Run Swagger Tests
      run: go test -v -tags=swagger ./...
      env:
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        DB_HOST: localhost
        MYSQL_DATABASE: stocks